spring:
  jackson:
   serialization:
     FAIL_ON_EMPTY_BEANS: false
logging:
  level:
    ROOT: INFO
web:
  cors:
    allowed-origins: "http://www.x-workz.in"
    allowed-methods: GET, POST, PUT, DELETE,
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"

    